package com.tushar.repo;

import org.springframework.data.jpa.repository.JpaRepository;

import com.tushar.entity.Student;

public interface StudentRepo extends JpaRepository<Student, Integer> {

	/*
	1)RETURNING MultiRowResult
	CREATE OR REPLACE PROCEDURE PRC_GET_STUDENT_BY_MARKS
	(
	MINMARKS IN FLOAT,
	MAXMARKS IN FLOAT,
	DETAILS OUT SYS_REFCURSOR
	) AS
	BEGIN
	OPEN DETAILS FOR 
	SELECT SID, SNAME, MARKS, RESULT FROM STUDENT WHERE MARKS>=MINMARKS AND MARKS<=MAXMARKS;
	END;
	/

	2)RETURNING SingularValuesResult
	CREATE OR REPLACE PROCEDURE PRC_IS_USER_VALID
	(
	USID IN number,
	PASSWD IN VARCHAR2,
	RESULT OUT VARCHAR2
	) AS
	CNT NUMBER(5);
	BEGIN
	SELECT COUNT(*) INTO CNT FROM STUDENT WHERE SID=USID AND SNAME=PASSWD;
	IF(CNT<>0) THEN
	RESULT:='VALID STUDENT';
	ELSE
	RESULT:='INVALID STUDENT';
	END IF;
	END;
	/

	3)RETURNING SingleRowResult
	CREATE OR REPLACE PROCEDURE PRC_GET_STUDENT_BY_ROLL
	(
	ROLL IN NUMBER,
	DETAILS OUT SYS_REFCURSOR
	) AS
	BEGIN
	OPEN DETAILS FOR 
	SELECT SID, SNAME, MARKS, RESULT FROM STUDENT WHERE SID=ROLL;
	END;
	/
	
	CREATE OR REPLACE FUNCTION FX_GET_STUDENT_DETAILS
(
IID IN NUMBER,
ONAME OUT VARCHAR2,
ORESULT OUT VARCHAR2
)RETURN NUMBER
AS
OMARKS NUMBER(4);
BEGIN
SELECT SID, SNAME, MARKS, RESULT INTO IID,ONAME,OMARKS,ORESULT FROM STUDENT WHERE SID=IID;
RETURN OMARKS;
END;
/
 * 
	*/
	
}
